docs: adds context configuration for spies
mobxjs/mobx.dart pull request #721
Opened 2021-12-21 01:05 UTC by Ascenio

Hello :wave: 

I've noticed that the section about _spying_ in the docs is somewhat incomplete because **mainContext**'s `isSpyEnabled` defaults to false, so if the user bindly copy the samples they won't work.

2021-12-21 02:02 UTC, Ascenio commented
Hey, @pavanpodila. Could you, please, re-run the CI? #722 has it fixed it! ;D

2021-12-21 09:08 UTC, pavanpodila requested changes

2021-12-21 09:08 UTC, pavanpodila commented on docs/docs/api/spy.mdx
> +Notice that before we spy on events, we must firstly make sure we enable
Minor grammar fix:

**"we must first make sure that spying is enabled."**

2021-12-23 07:10 UTC, pavanpodila requested changes

2021-12-23 07:10 UTC, pavanpodila commented on mobx/lib/src/api/observable_collections/observable_map.dart
> +    final castedKey = key as K?;
Please update from master to change these lines. We are adopting a slightly different approach

2021-12-23 07:27 UTC, merged