Routine PR (2022.03.18)
mobxjs/mobx.dart pull request #778
Opened 2022-03-18 12:51 UTC by fzyzcjy

Closes #777

2022-04-05 01:37 UTC, fzyzcjy commented
Seems to need a review before this can be merged (after a few weeks)

2022-04-13 05:42 UTC, pavanpodila requested changes
Changelog entry and version upgrade must be made for this. Please run set-versions via npm as well

2022-04-13 05:42 UTC, pavanpodila commented on flutter_mobx/lib/src/observer_widget_mixin.dart
> +          'Error happens when building ${_widget.runtimeType}, but it was captured since disableErrorBoundaries==true');
the english is not clear. It has to be described in the past tense.

2022-04-13 05:42 UTC, pavanpodila commented on flutter_mobx/test/flutter_mobx_test.dart
> +        'Error happens when building Observer, but it was captured since disableErrorBoundaries==true');
English should be written in past tense for this test

2022-04-18 08:42 UTC, fzyzcjy commented
Oh I forgot it... Will do it today

2022-04-18 08:59 UTC, fzyzcjy commented
Done. 

@pavanpodila May I know what is "npm set-version"? I have checked `docs/package.json`, google it, and search through repo without finding it.

2022-04-18 09:29 UTC, fzyzcjy commented
Done. @pavanpodila

2022-04-21 05:06 UTC, pavanpodila approved these changes

2022-04-21 05:06 UTC, merged