Observable extensions
mobxjs/mobx.dart pull request #792
Opened 2022-04-11 19:57 UTC by subzero911

Dear MobX maintainers, I created some extensions to make a code more concise. I hope you find them useful.
1. Type aliases for primitive types.
So instead of Observable<int> you can write ObservableInt.
But it uses the Dart 2.13 feature "type aliases", so I bumped sdk constraints in pubspec to min 2.13
3. asObservable() extensions for primitive types. Now you can easily convert literals to observables like:
`''.asObservable()`
`42.asObservable()`

2022-04-12 02:23 UTC, pavanpodila requested changes
Please update the version in pubspec and bump the minor version. Also run set-version command in package.Json. additionally we should add an entry inn change log for this

2022-04-12 07:14 UTC, subzero911 commented
I bumped the version in pubspec.

But I don't know how to run a set-version command. Is it some npm thing?

2022-04-12 10:44 UTC, subzero911 commented
I runned `npm version 1.0.1`, is it what you wanted?

2022-04-12 10:44 UTC, subzero911 commented
@pavanpodila I runned `npm version 1.0.1`, is it what you wanted?

2022-04-12 10:49 UTC, subzero911 commented
okay, I see
I run `npm run set:versions` and updated a version in mobx.dart

2022-04-13 05:39 UTC, pavanpodila requested changes
We need to add a Changelog entry as well for the new version

2022-04-13 19:58 UTC, subzero911 commented
added

2022-04-18 08:34 UTC, subzero911 commented
@pavanpodila anything else?

2022-04-21 04:27 UTC, pavanpodila requested changes

2022-04-21 04:27 UTC, pavanpodila commented on mobx/CHANGELOG.md
> +- `toggle()` method for ObservableBool. Lets you toggle the internal value of ObservableBool
ObservableBool should be in back quotes

2022-04-21 07:45 UTC, subzero911 commented on mobx/CHANGELOG.md
> +- `toggle()` method for ObservableBool. Lets you toggle the internal value of ObservableBool
+

2022-04-21 09:19 UTC, pavanpodila approved these changes

2022-04-21 09:20 UTC, merged

2022-04-21 09:20 UTC, pavanpodila commented
@all-contributors add @subzero911 for code