Add no_leading_underscores rule to ignore_for_file in mobx_codegen
mobxjs/mobx.dart pull request #817
Opened 2022-05-16 21:26 UTC by ko16a46

Recommended rules from the `lints` package now include the `no_leading_underscores_for_local_identifiers` rule

The default generated store code with actions breaks this rule, causing the linter to complain

Add the rule to the ignore_for_file part of the template, to pacify the analyzer

Fixes #816

2022-05-16 21:47 UTC, fzyzcjy commented
LGTM, btw you should bump the version

2022-05-16 21:48 UTC, fzyzcjy commented
@pavanpodila Shall we modify the `PR template` such that there is a tickbox for "you have bumped the version", otherwise reviewers have to say it again and again

2022-05-16 22:00 UTC, ko16a46 commented
Thanks! I bumped the version and added a changelog entry accordingly

2022-05-17 02:32 UTC, pavanpodila commented
> @pavanpodila Shall we modify the `PR template` such that there is a tickbox for "you have bumped the version", otherwise reviewers have to say it again and again

Yes please. Can we create a template for this? There are few other instructions around change log, use of set versions command etc.

2022-05-17 02:39 UTC, fzyzcjy commented
> Can we create a template for this?

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

2022-05-17 03:48 UTC, pavanpodila requested changes
Pls run the set:versions command from npm to change the version string in the lib/mobx_codegen.dart

2022-05-17 07:00 UTC, ko16a46 commented
Got it, ran the set:version command using npm and committed the changes, thanks

2022-05-17 09:52 UTC, merged

2022-05-17 09:52 UTC, pavanpodila commented
@all-contributors add @ko16a46 for code