🐛 Fixes issue in ObservableList while using Iterables.
mobxjs/mobx.dart pull request #942
Opened 2023-10-14 21:35 UTC by ParthBaraiya

Describe the changes proposed in this Pull Request.

This PR Fixes issue #941 .

---
## Pull Request Checklist

- [ ] If the changes are being made to code, ensure the **version in `pubspec.yaml`** is updated. 
- [ ] Increment the **`major`/`minor`/`patch`/`patch-count`**, depending on the complexity of change
- [ ] Add the necessary **unit tests** to ensure the coverage does not drop
- [ ] Update the **Changelog** to include all changes made in this PR, organized by version
- [ ] Run the **`melo run set_version` command** from the root directory
- [ ] Include the **necessary reviewers** for the PR
- [ ] Update the docs if there are any API changes or additions to functionality

2023-10-16 10:48 UTC, pavanpodila requested changes
Also need pubspec update, changelog and running the `melos run set_version` command to update the `lib/mobx.dart` file

2023-10-16 10:48 UTC, pavanpodila commented on mobx/lib/src/api/observable_collections/observable_list.dart
>          final newValues = iterable.toList(growable: false);
`newValues` can be created first and then used to fetch the `length`. That way the previous call on `iterable.length` is not needed (which actually forces a complete walk of the iterable)

2023-10-16 14:30 UTC, ParthBaraiya commented
Hi @pavanpodila , I've made necessary changes in the PR 

But while running `melos run set_version` command it was not doing anything but to open `expose_version.dart` file in Text editor. So, I had to update the `melos.yaml` file as well. Hope that's OK.

2023-10-16 14:37 UTC, ParthBaraiya commented
Also, I was not able to use the latest version of melos. Because latest version requires melos package added in `pubspec.yaml` and root folder doesn't have `pubspec.yaml` file.

2023-10-17 03:31 UTC, pavanpodila requested changes
thanks for fixing the melos script. We have one change in flutter_mobx due to a lagging version update. Can you please include a small changelog for that..might require reading the git log

2023-10-17 03:31 UTC, pavanpodila commented on flutter_mobx/lib/version.dart
> -const version = '2.0.6+5';
looks like this version was lagging behind and got updated once the set_version was run. Could you please include a changelog entry for this by reading the changes done in the past version.

2023-10-17 03:34 UTC, pavanpodila commented
one of the test has failed with this change. pls see @ParthBaraiya

2023-10-17 15:42 UTC, ParthBaraiya commented
> thanks for fixing the melos script. We have one change in flutter_mobx due to a lagging version update. Can you please include a small changelog for that..might require reading the git log

Looks like you have already merged a changes for this on master.

2023-10-17 15:44 UTC, ParthBaraiya commented
> one of the test has failed with this change. pls see @ParthBaraiya

This is fixed.

2023-10-18 10:21 UTC, merged

2023-10-18 10:21 UTC, pavanpodila commented
@all-contributors add @ParthBaraiya for code, bug