Observer.optimized
mobxjs/mobx.dart pull request #952
Opened 2023-11-06 11:33 UTC by subzero911

I already did a PR https://github.com/mobxjs/mobx.dart/pull/909 but I accidentally deleted the forked repo.
So I made it again and a little bit better.

Mostly you try to make Observer as small as possible. But sometimes you'll want to exclude the widget subtree from re-render and improve the performance.

Real world examples:
1) You have a colored Container with some heavy widgets inside (like `ListView` with `shrinkWrap: true`).
You want to change the color by Observable, but don't want to rebuild the whole ListView.
2) You have some fancy animation driven by Observable. You want to animate the widget and want to preserve its children from being rebuilt.

I introduce the new `Observer.optimized` which allows you to exclude the `child` branch.
Usage:
   ```dart
   Observer.optimized(
     builderOptimized: (context, child) => FooWidget(foo: foo, child: child),
     child: BarWidget(), // is not rebuilt
   ),
   ``` 

Solves https://github.com/mobxjs/mobx.dart/issues/551

@amondnet @fzyzcjy 

---
## Pull Request Checklist

- [x] If the changes are being made to code, ensure the **version in `pubspec.yaml`** is updated. 
- [x] Increment the **`major`/`minor`/`patch`/`patch-count`**, depending on the complexity of change
- [x] Add the necessary **unit tests** to ensure the coverage does not drop
- [x] Update the **Changelog** to include all changes made in this PR, organized by version
- [x] Run the **`melos run set_version` command** from the root directory
- [x] Include the **necessary reviewers** for the PR
- [x] Update the **docs** if there are any API changes or additions to functionality

2023-11-08 12:37 UTC, pavanpodila requested changes

2023-11-08 12:37 UTC, pavanpodila commented on flutter_mobx/lib/src/observer.dart
> +  Observer.optimized({
We should call this `withChild` to make the intent clear. The idea is to only build parts that are actually changing and keeping rest of the tree intact. I think you would also need a `withChildren` variant as well which could be a `Map<String, Widget>`?. This variant will help in plugging in parts of the tree which are not changing. This is useful when you have more than one child.

2023-11-19 10:23 UTC, subzero911 commented
@pavanpodila done. I renamed `.optimized` to `.withChild` and `builderOptimized` to `builderWithChild`
I have no idea how to implement "withChildren" constructor to "exclude subtrees by map keys", and I don't think we actually need it. You can use a `Column(children: [...])` as a `child`, or you can use a composition of Observers.
I applied the same technique which was used in AnimatedBuilder, and `provider`'s `Consumer` and `Selector` - they all have the `child` parameter only. They don't have multiple children version. Check https://api.flutter.dev/flutter/widgets/AnimatedBuilder-class.html , "Performance optimizations" for details

2023-11-19 12:55 UTC, pavanpodila approved these changes

2023-11-19 12:55 UTC, merged

2023-11-19 13:00 UTC, pavanpodila commented
@all_contributors add @subzero911 for code

2023-11-19 13:02 UTC, pavanpodila commented
@all-contributors add @subzero911 for code