feat: add keepAlive to Computed
mobxjs/mobx.dart pull request #976
Opened 2023-12-19 10:58 UTC by amondnet

Describe the changes proposed in this Pull Request.

If the PR fixes a specific issue, reference the issue with **`Fixes #`**.

---
## Pull Request Checklist

- [ ] If the changes are being made to code, ensure the **version in `pubspec.yaml`** is updated. 
- [ ] Increment the **`major`/`minor`/`patch`/`patch-count`**, depending on the complexity of change
- [ ] Add the necessary **unit tests** to ensure the coverage does not drop
- [ ] Update the **Changelog** to include all changes made in this PR, organized by version
- [ ] Run the **`melos run set_version` command** from the root directory
- [ ] Include the **necessary reviewers** for the PR
- [ ] Update the **docs** if there are any API changes or additions to functionality

2023-12-21 05:41 UTC, pavanpodila commented
Pls resolve the conflicts as we merged the previous PR that bumped the version

2023-12-21 05:45 UTC, pavanpodila requested changes
looks good overall..need a version bump...also pls check if there is any drop in test coverage

2023-12-27 06:05 UTC, amondnet commented
@pavanpodila I rebased to the main branch and resolved the conflict.

2023-12-27 10:41 UTC, pavanpodila requested changes

2023-12-27 10:41 UTC, pavanpodila commented on mobx/CHANGELOG.md
> +- Add `keepAlive` to `Computed` to avoids suspending computed values when they are not being observed by anything.
avoid instead of avoids

2023-12-27 12:13 UTC, pavanpodila approved these changes

2023-12-27 12:13 UTC, merged